### ISSUE TITLE
monitor-index-creation isn't Python 2.7 compatible

### ISSUE THREAD

**Issue by the-allanc** [jaraco/jaraco.mongodb#19]
As far as I can see, jaraco.mongodb is meant to be entirely Python 2.7 compatible, but that script uses a print function without doing the special `from __future__ import print_function` dance. Could we change that?

**Comment by jaraco** [comment]
I'm dropping support for Python 2.7 wherever possible. I'm encouraging others to use Python 3 also. In many projects, I've started creating scripts in a Python 2-compatible package that are themselves only Python 3 compatible. I'd recommend instead using rwt to run the script:

```
python3 -m rwt jaraco.mongodb -- -m jaraco.mongodb.monitor-index-creation ...
```

But since you asked, and in order not to be hostile to our users stuck on Python 2, I'll make it compatible.

**Comment by jaraco** [comment]
hrm. But what if I wanted to use autocommand on the script, which I do?

**Comment by jaraco** [comment]
I guess I'll abandon that hope for now.

**Comment by jaraco** [comment]
Going out as the 7.8 release.

**Comment by the-allanc** [comment]
I hadn't heard of autocommand since you started using it. I feel torn between making use of that and using "argh" instead if I need what I'm writing to be Python 2.7 compatible.

Anyway - I appreciate you doing this; especially as I wasn't _actually_ using the script. But I do have an old project which I'm trying to move to Python 3 (you know the one) and I have a build step which tries to compile all the dependencies in the local version of Python, so I can detect incompatible dependencies earlier.

Currently - it's flagging up problems with projects that aren't Python 3 compatible (which is my main goal), but this module was the only one being flagged up as being Python 2 incompatible.

!m jaraco
